"""complete compliance domain

Revision ID: a723c7e5cafd
Revises: b77bd630b8da
Create Date: 2026-08-30 15:37:34.011238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a723c7e5cafd'
down_revision: Union[str, Sequence[str], None] = 'b77bd630b8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_applicability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_applicability_rule_version_id'), 'rule_applicability', ['rule_version_id'], unique=False)
    op.create_table('rule_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rule_version_id <> depends_on_rule_version_id', name='ck_rule_dependency_not_self'),
    sa.ForeignKeyConstraint(['depends_on_rule_version_id'], ['rule_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_dependencies_depends_on_rule_version_id'), 'rule_dependencies', ['depends_on_rule_version_id'], unique=False)
    op.create_index(op.f('ix_rule_dependencies_rule_version_id'), 'rule_dependencies', ['rule_version_id'], unique=False)
    op.create_index('uq_rule_dependency', 'rule_dependencies', ['rule_version_id', 'depends_on_rule_version_id'], unique=True)
    op.create_table('compliance_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('outcome', sa.Enum('PASS', 'FAIL', 'NEEDS_REVIEW', 'NOT_APPLICABLE', name='compliance_outcome'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('dependency_affected', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_results_project_id'), 'compliance_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_rule_version_id'), 'compliance_results', ['rule_version_id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('canonical_value', sa.Text(), nullable=True),
    sa.Column('conflicting_values', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancies_project_id'), 'discrepancies', ['project_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('compliance_result_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compliance_result_id'], ['compliance_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_compliance_result_id'), 'findings', ['compliance_result_id'], unique=False)
    op.create_index('uq_rule_version_number', 'rule_versions', ['rule_id', 'version_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_rule_version_number', table_name='rule_versions')
    op.drop_index(op.f('ix_findings_compliance_result_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_discrepancies_project_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_compliance_results_rule_version_id'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_project_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index('uq_rule_dependency', table_name='rule_dependencies')
    op.drop_index(op.f('ix_rule_dependencies_rule_version_id'), table_name='rule_dependencies')
    op.drop_index(op.f('ix_rule_dependencies_depends_on_rule_version_id'), table_name='rule_dependencies')
    op.drop_table('rule_dependencies')
    op.drop_index(op.f('ix_rule_applicability_rule_version_id'), table_name='rule_applicability')
    op.drop_table('rule_applicability')
    # ### end Alembic commands ###
