"""create project property hierarchy

Revision ID: f4389b6f5a25
Revises: 8cd5cd6de10d
Create Date: 2026-08-29 11:32:07.753834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4389b6f5a25'
down_revision: Union[str, Sequence[str], None] = '8cd5cd6de10d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('builder_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.Enum('APARTMENT', 'VILLA', 'INDIVIDUAL_HOUSE', name='project_type'), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['builder_id'], ['builder_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_builder_id'), 'projects', ['builder_id'], unique=False)
    op.create_table('project_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'SUPERSEDED', name='project_version_status'), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_versions_project_id'), 'project_versions', ['project_id'], unique=False)
    op.create_index('uq_project_pending_approval', 'project_versions', ['project_id'], unique=True, postgresql_where=sa.text("status = 'PENDING_APPROVAL'"))
    op.create_index('uq_project_version_number', 'project_versions', ['project_id', 'version_number'], unique=True)
    op.create_table('buildings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('building_number', sa.String(length=100), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_version_id'], ['project_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_project_version_id'), 'buildings', ['project_version_id'], unique=False)
    op.create_table('units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('unit_number', sa.String(length=100), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('unit_type', sa.String(length=100), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_building_id'), 'units', ['building_id'], unique=False)
    op.create_index('uq_building_unit_number', 'units', ['building_id', 'unit_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_building_unit_number', table_name='units')
    op.drop_index(op.f('ix_units_building_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_buildings_project_version_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index('uq_project_version_number', table_name='project_versions')
    op.drop_index('uq_project_pending_approval', table_name='project_versions', postgresql_where=sa.text("status = 'PENDING_APPROVAL'"))
    op.drop_index(op.f('ix_project_versions_project_id'), table_name='project_versions')
    op.drop_table('project_versions')
    op.drop_index(op.f('ix_projects_builder_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
